### PR TITLE
Kalman Filter update

### PR DESCRIPTION
**Pull request by Allen-ENGI**
Hello, I put all the necessary codes and the testing video in the file. There is also a description.md for the explanation.

### CODE REVIEW

**Comment by Bill-Haoyu-Lin** [comment]
Can you provide some supporting testing information thanks! (for example video of result) Great work! 
Also can you use armor plate instead of orange?

**Review by Bill-Haoyu-Lin — CHANGES_REQUESTED** [review]
Code need to be changed to fit RM armor plate detection, instead of detecting an orange

**Comment by Allen-ENGI** [comment]
I have deleted the useless functions and changed the description.txt.

**Comment by Bill-Haoyu-Lin** [comment]
Great work! Can we have some testing record/data? (please include the code on demo in comment session) Thanks

**Comment by Allen-ENGI** [comment]
Ok, I will update the file

**Comment by Bill-Haoyu-Lin** [comment]
> Ok, I will update the file

Have something like "how to use it in our code" will be really helpful. I have no idea how to use it now

**Comment by Allen-ENGI** [comment]
> > Ok, I will update the file
> 
> Have something like "how to use it in our code" will be really helpful. I have no idea how to use it now

Will add that part to description.md, thanks for bringing it up.

**Comment by Bill-Haoyu-Lin** [comment]
> > > Ok, I will update the file
> > 
> > 
> > Have something like "how to use it in our code" will be really helpful. I have no idea how to use it now
> 
> Will add that part to description.md, thanks for bringing it up.

Or you can just put it on top of your code 
image

And remove the description.md put all information under this pull request comment or move it to code comment part
you can use this template
```
################################################
#function name:
#function description:
#function call demo code: 
################################################
```

**Comment by Allen-ENGI** [comment]
Removed the Folder and add commented to the kalmanfilter.py file

**Review by Bill-Haoyu-Lin — APPROVED** [review]

**Pull request merged**
